# cSpell:disable
name: urlshort

services:

  # LOAD BALANCER
  nginx-1:
    image: nginx
    container_name: nginx-1
    networks:
      - scylla
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      urlshort-server-1:
        condition: service_healthy
      urlshort-server-2:
        condition: service_healthy
      # urlshort-server-3:
      #   condition: service_healthy

  nginx-2:
    image: nginx
    container_name: nginx-2
    networks:
      - scylla
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      urlshort-server-1:
        condition: service_healthy
      urlshort-server-2:
        condition: service_healthy
      # urlshort-server-3:
      #   condition: service_healthy

  # DBs
  scylla-1:
    image: scylladb/scylla:latest
    container_name: scylla-1
    command: >
      --seeds=scylla-1
      --smp 1
      --memory 750M
      --overprovisioned 1
      --api-address 0.0.0.0
#      --listen_address 0.0.0.0
    # ports:
    #   - "9042:9042"
    #   - "10000:10000"
    volumes:
      - scylla1_data:/var/lib/scylla
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/system/uptime_ms"]
      #test: ["CMD-SHELL","cqlsh localhost 9042 -e 'SELECT now() FROM system.local;'"]

      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - scylla

  scylla-2:
    image: scylladb/scylla:latest
    container_name: scylla-2
    command: >
      --seeds=scylla-1
      --smp 1
      --memory 750M
      --overprovisioned 1
      --api-address 0.0.0.0
    # ports:
    #   - "9042:9042"
    #   - "10000:10000"
    volumes:
      - scylla2_data:/var/lib/scylla
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/system/uptime_ms"]
      #test: ["CMD-SHELL","cqlsh localhost 9042 -e 'SELECT now() FROM system.local;'"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - scylla
    depends_on:
      scylla-1:
        condition: service_healthy


  # scylla-3:
  #   image: scylladb/scylla:latest
  #   container_name: scylla-3
  #   command: >
  #     --seeds=scylla-1
  #     --smp 1
  #     --memory 750M
  #     --overprovisioned 1
  #     --api-address 0.0.0.0
  #   # ports:
  #   #   - "9042:9042"
  #   #   - "10000:10000"
  #   volumes:
  #     - scylla3_data:/var/lib/scylla
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:10000/"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 10
  #     start_period: 30s
  #   networks:
  #     - scylla
    # depends_on:
    #   - scylla-1
#        condition: service_healthy

  # CACHING
  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass redis_pass --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    restart: always
    ports:
      - "6379:6379"
    networks:
      - scylla
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5


  # WEB APPS
  urlshort-server-1:
    image: urlshort-server
    container_name: urlshort-server-1
    environment:
      SCYLLADB_KNOWN_NODES: scylla-1,scylla-2
      REDIS_URL: redis://redis/
      LISTEN_HOST: 0.0.0.0:80
      PUBLIC_URL: http://localhost
    networks:
      - scylla
    ports:
      - "8081:80"
    depends_on:
      #scylla-1:
      #  condition: service_healthy
      scylla-2:
        condition: service_healthy
      # scylla-3:
      #   condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/v1/health"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s

  urlshort-server-2:
    container_name: urlshort-server-2
    image: urlshort-server
    environment:
      SCYLLADB_KNOWN_NODES: scylla-1,scylla-2
      REDIS_URL: redis://redis/
      LISTEN_HOST: 0.0.0.0:80
      PUBLIC_URL: http://localhost/
    networks:
      - scylla
    ports:
      - "8082:80"
    depends_on:
      scylla-1:
        condition: service_healthy
      scylla-2:
        condition: service_healthy
      # scylla-3:
      #   condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/v1/health"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s


  # urlshort-server-3:
  #   container_name: urlshort-server-3
  #   image: urlshort-server
  #   environment:
  #     SCYLLADB_KNOWN_NODES: scylla-1,scylla-2,scylla-3
  #     REDIS_URL: redis://redis/
  #     LISTEN_HOST: 0.0.0.0:80
  #     PUBLIC_URL: http://localhost/
  #   networks:
  #     - scylla
  #   ports:
  #     - "8083:80"
  #   depends_on:
  #     scylla-1:
  #       condition: service_healthy
  #     scylla-2:
  #       condition: service_healthy
  #     scylla-3:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost/api/v1/health"]
  #     interval: 30s
  #     timeout: 30s
  #     retries: 5
  #     start_period: 30s


networks:
 scylla:

volumes:
  redis_data:
  scylla1_data:
  scylla2_data:
#  scylla3_data:
